package com.pactera.edg.am.metamanager.extractor.adapter.extract.powerCenter.transformation;

import java.util.List;
import java.util.Set;

import org.jdom.Element;
import org.jdom.JDOMException;
import org.jdom.xpath.XPath;

public class RouterTransform extends AbstractTransform {
	/*
	 *  <TRANSFORMATION DESCRIPTION ="" NAME ="RTRTRANS" OBJECTVERSION ="1" REUSABLE ="NO" TYPE ="Router" VERSIONNUMBER ="3">
            <GROUP DESCRIPTION ="" NAME ="INPUT" ORDER ="1" TYPE ="INPUT"/>
            <GROUP DESCRIPTION ="" EXPRESSION ="PARAMETER_TYPE=1" NAME ="workflow_para" ORDER ="2" TYPE ="OUTPUT"/>
            <GROUP DESCRIPTION ="Path for the data when none of the group conditions are satisfied." NAME ="DEFAULT" ORDER ="7" TYPE ="OUTPUT/DEFAULT"/>
            <GROUP DESCRIPTION ="" EXPRESSION ="PARAMETER_TYPE=2" NAME ="worklet_para" ORDER ="3" TYPE ="OUTPUT"/>
            <GROUP DESCRIPTION ="" EXPRESSION ="PARAMETER_TYPE=3  OR  PARAMETER_TYPE=4 OR PARAMETER_TYPE=5" NAME ="mapping_and_session_para" ORDER ="4" TYPE ="OUTPUT"/>
            <TRANSFORMFIELD DATATYPE ="string" DEFAULTVALUE ="" DESCRIPTION ="" GROUP ="INPUT" NAME ="FOLDER_NAME" PICTURETEXT ="" PORTTYPE ="INPUT" PRECISION ="50" SCALE ="0"/>
            <TRANSFORMFIELD DATATYPE ="string" DEFAULTVALUE ="" DESCRIPTION ="" GROUP ="INPUT" NAME ="WORKFLOW_NAME" PICTURETEXT ="" PORTTYPE ="INPUT" PRECISION ="50" SCALE ="0"/>
            <TRANSFORMFIELD DATATYPE ="string" DEFAULTVALUE ="" DESCRIPTION ="" GROUP ="INPUT" NAME ="SESSION_NAME" PICTURETEXT ="" PORTTYPE ="INPUT" PRECISION ="150" SCALE ="0"/>
            <TRANSFORMFIELD DATATYPE ="string" DEFAULTVALUE ="" DESCRIPTION ="" GROUP ="INPUT" NAME ="PARAMETER_NAME" PICTURETEXT ="" PORTTYPE ="INPUT" PRECISION ="50" SCALE ="0"/>
            <TRANSFORMFIELD DATATYPE ="integer" DEFAULTVALUE ="" DESCRIPTION ="" GROUP ="INPUT" NAME ="PARAMETER_TYPE" PICTURETEXT ="" PORTTYPE ="INPUT" PRECISION ="10" SCALE ="0"/>
            <TRANSFORMFIELD DATATYPE ="string" DEFAULTVALUE ="" DESCRIPTION ="" GROUP ="INPUT" NAME ="PARAMETER_VALUE" PICTURETEXT ="" PORTTYPE ="INPUT" PRECISION ="150" SCALE ="0"/>
            <TRANSFORMFIELD DATATYPE ="string" DEFAULTVALUE ="" DESCRIPTION ="" GROUP ="INPUT" NAME ="MAPPLET_NAME" PICTURETEXT ="" PORTTYPE ="INPUT" PRECISION ="50" SCALE ="0"/>
            <TRANSFORMFIELD DATATYPE ="string" DEFAULTVALUE ="" DESCRIPTION ="" GROUP ="INPUT" NAME ="DATADATE" PICTURETEXT ="" PORTTYPE ="INPUT" PRECISION ="19" SCALE ="0"/>
            <TRANSFORMFIELD DATATYPE ="string" DEFAULTVALUE ="" DESCRIPTION ="" GROUP ="workflow_para" NAME ="FOLDER_NAME1" PICTURETEXT ="" PORTTYPE ="OUTPUT" PRECISION ="50" REF_FIELD ="FOLDER_NAME" SCALE ="0"/>
            <TRANSFORMFIELD DATATYPE ="string" DEFAULTVALUE ="" DESCRIPTION ="" GROUP ="workflow_para" NAME ="WORKFLOW_NAME1" PICTURETEXT ="" PORTTYPE ="OUTPUT" PRECISION ="50" REF_FIELD ="WORKFLOW_NAME" SCALE ="0"/>
            <TRANSFORMFIELD DATATYPE ="string" DEFAULTVALUE ="" DESCRIPTION ="" GROUP ="workflow_para" NAME ="SESSION_NAME1" PICTURETEXT ="" PORTTYPE ="OUTPUT" PRECISION ="150" REF_FIELD ="SESSION_NAME" SCALE ="0"/>
            <TRANSFORMFIELD DATATYPE ="string" DEFAULTVALUE ="" DESCRIPTION ="" GROUP ="workflow_para" NAME ="PARAMETER_NAME1" PICTURETEXT ="" PORTTYPE ="OUTPUT" PRECISION ="50" REF_FIELD ="PARAMETER_NAME" SCALE ="0"/>
            <TRANSFORMFIELD DATATYPE ="integer" DEFAULTVALUE ="" DESCRIPTION ="" GROUP ="workflow_para" NAME ="PARAMETER_TYPE1" PICTURETEXT ="" PORTTYPE ="OUTPUT" PRECISION ="10" REF_FIELD ="PARAMETER_TYPE" SCALE ="0"/>
            <TRANSFORMFIELD DATATYPE ="string" DEFAULTVALUE ="" DESCRIPTION ="" GROUP ="workflow_para" NAME ="PARAMETER_VALUE1" PICTURETEXT ="" PORTTYPE ="OUTPUT" PRECISION ="150" REF_FIELD ="PARAMETER_VALUE" SCALE ="0"/>
            <TRANSFORMFIELD DATATYPE ="string" DEFAULTVALUE ="" DESCRIPTION ="" GROUP ="workflow_para" NAME ="MAPPLET_NAME1" PICTURETEXT ="" PORTTYPE ="OUTPUT" PRECISION ="50" REF_FIELD ="MAPPLET_NAME" SCALE ="0"/>
            <TRANSFORMFIELD DATATYPE ="string" DEFAULTVALUE ="" DESCRIPTION ="" GROUP ="workflow_para" NAME ="DATADATE1" PICTURETEXT ="" PORTTYPE ="OUTPUT" PRECISION ="19" REF_FIELD ="DATADATE" SCALE ="0"/>
            <TRANSFORMFIELD DATATYPE ="string" DEFAULTVALUE ="" DESCRIPTION ="" GROUP ="worklet_para" NAME ="FOLDER_NAME3" PICTURETEXT ="" PORTTYPE ="OUTPUT" PRECISION ="50" REF_FIELD ="FOLDER_NAME" SCALE ="0"/>
            <TRANSFORMFIELD DATATYPE ="string" DEFAULTVALUE ="" DESCRIPTION ="" GROUP ="worklet_para" NAME ="WORKFLOW_NAME3" PICTURETEXT ="" PORTTYPE ="OUTPUT" PRECISION ="50" REF_FIELD ="WORKFLOW_NAME" SCALE ="0"/>
            <TRANSFORMFIELD DATATYPE ="string" DEFAULTVALUE ="" DESCRIPTION ="" GROUP ="worklet_para" NAME ="SESSION_NAME3" PICTURETEXT ="" PORTTYPE ="OUTPUT" PRECISION ="150" REF_FIELD ="SESSION_NAME" SCALE ="0"/>
            <TRANSFORMFIELD DATATYPE ="string" DEFAULTVALUE ="" DESCRIPTION ="" GROUP ="worklet_para" NAME ="PARAMETER_NAME3" PICTURETEXT ="" PORTTYPE ="OUTPUT" PRECISION ="50" REF_FIELD ="PARAMETER_NAME" SCALE ="0"/>
            <TRANSFORMFIELD DATATYPE ="integer" DEFAULTVALUE ="" DESCRIPTION ="" GROUP ="worklet_para" NAME ="PARAMETER_TYPE3" PICTURETEXT ="" PORTTYPE ="OUTPUT" PRECISION ="10" REF_FIELD ="PARAMETER_TYPE" SCALE ="0"/>
            <TRANSFORMFIELD DATATYPE ="string" DEFAULTVALUE ="" DESCRIPTION ="" GROUP ="worklet_para" NAME ="PARAMETER_VALUE3" PICTURETEXT ="" PORTTYPE ="OUTPUT" PRECISION ="150" REF_FIELD ="PARAMETER_VALUE" SCALE ="0"/>
            <TRANSFORMFIELD DATATYPE ="string" DEFAULTVALUE ="" DESCRIPTION ="" GROUP ="worklet_para" NAME ="MAPPLET_NAME3" PICTURETEXT ="" PORTTYPE ="OUTPUT" PRECISION ="50" REF_FIELD ="MAPPLET_NAME" SCALE ="0"/>
            <TRANSFORMFIELD DATATYPE ="string" DEFAULTVALUE ="" DESCRIPTION ="" GROUP ="worklet_para" NAME ="DATADATE3" PICTURETEXT ="" PORTTYPE ="OUTPUT" PRECISION ="19" REF_FIELD ="DATADATE" SCALE ="0"/>
            <TRANSFORMFIELD DATATYPE ="string" DEFAULTVALUE ="" DESCRIPTION ="" GROUP ="mapping_and_session_para" NAME ="FOLDER_NAME4" PICTURETEXT ="" PORTTYPE ="OUTPUT" PRECISION ="50" REF_FIELD ="FOLDER_NAME" SCALE ="0"/>
            <TRANSFORMFIELD DATATYPE ="string" DEFAULTVALUE ="" DESCRIPTION ="" GROUP ="mapping_and_session_para" NAME ="WORKFLOW_NAME4" PICTURETEXT ="" PORTTYPE ="OUTPUT" PRECISION ="50" REF_FIELD ="WORKFLOW_NAME" SCALE ="0"/>
            <TRANSFORMFIELD DATATYPE ="string" DEFAULTVALUE ="" DESCRIPTION ="" GROUP ="mapping_and_session_para" NAME ="SESSION_NAME4" PICTURETEXT ="" PORTTYPE ="OUTPUT" PRECISION ="150" REF_FIELD ="SESSION_NAME" SCALE ="0"/>
            <TRANSFORMFIELD DATATYPE ="string" DEFAULTVALUE ="" DESCRIPTION ="" GROUP ="mapping_and_session_para" NAME ="PARAMETER_NAME4" PICTURETEXT ="" PORTTYPE ="OUTPUT" PRECISION ="50" REF_FIELD ="PARAMETER_NAME" SCALE ="0"/>
            <TRANSFORMFIELD DATATYPE ="integer" DEFAULTVALUE ="" DESCRIPTION ="" GROUP ="mapping_and_session_para" NAME ="PARAMETER_TYPE4" PICTURETEXT ="" PORTTYPE ="OUTPUT" PRECISION ="10" REF_FIELD ="PARAMETER_TYPE" SCALE ="0"/>
            <TRANSFORMFIELD DATATYPE ="string" DEFAULTVALUE ="" DESCRIPTION ="" GROUP ="mapping_and_session_para" NAME ="PARAMETER_VALUE4" PICTURETEXT ="" PORTTYPE ="OUTPUT" PRECISION ="150" REF_FIELD ="PARAMETER_VALUE" SCALE ="0"/>
            <TRANSFORMFIELD DATATYPE ="string" DEFAULTVALUE ="" DESCRIPTION ="" GROUP ="mapping_and_session_para" NAME ="MAPPLET_NAME4" PICTURETEXT ="" PORTTYPE ="OUTPUT" PRECISION ="50" REF_FIELD ="MAPPLET_NAME" SCALE ="0"/>
            <TRANSFORMFIELD DATATYPE ="string" DEFAULTVALUE ="" DESCRIPTION ="" GROUP ="mapping_and_session_para" NAME ="DATADATE4" PICTURETEXT ="" PORTTYPE ="OUTPUT" PRECISION ="19" REF_FIELD ="DATADATE" SCALE ="0"/>
            <TRANSFORMFIELD DATATYPE ="string" DEFAULTVALUE ="" DESCRIPTION ="" GROUP ="DEFAULT" NAME ="FOLDER_NAME2" PICTURETEXT ="" PORTTYPE ="OUTPUT" PRECISION ="50" REF_FIELD ="FOLDER_NAME" SCALE ="0"/>
            <TRANSFORMFIELD DATATYPE ="string" DEFAULTVALUE ="" DESCRIPTION ="" GROUP ="DEFAULT" NAME ="WORKFLOW_NAME2" PICTURETEXT ="" PORTTYPE ="OUTPUT" PRECISION ="50" REF_FIELD ="WORKFLOW_NAME" SCALE ="0"/>
            <TRANSFORMFIELD DATATYPE ="string" DEFAULTVALUE ="" DESCRIPTION ="" GROUP ="DEFAULT" NAME ="SESSION_NAME2" PICTURETEXT ="" PORTTYPE ="OUTPUT" PRECISION ="150" REF_FIELD ="SESSION_NAME" SCALE ="0"/>
            <TRANSFORMFIELD DATATYPE ="string" DEFAULTVALUE ="" DESCRIPTION ="" GROUP ="DEFAULT" NAME ="PARAMETER_NAME2" PICTURETEXT ="" PORTTYPE ="OUTPUT" PRECISION ="50" REF_FIELD ="PARAMETER_NAME" SCALE ="0"/>
            <TRANSFORMFIELD DATATYPE ="integer" DEFAULTVALUE ="" DESCRIPTION ="" GROUP ="DEFAULT" NAME ="PARAMETER_TYPE2" PICTURETEXT ="" PORTTYPE ="OUTPUT" PRECISION ="10" REF_FIELD ="PARAMETER_TYPE" SCALE ="0"/>
            <TRANSFORMFIELD DATATYPE ="string" DEFAULTVALUE ="" DESCRIPTION ="" GROUP ="DEFAULT" NAME ="PARAMETER_VALUE2" PICTURETEXT ="" PORTTYPE ="OUTPUT" PRECISION ="150" REF_FIELD ="PARAMETER_VALUE" SCALE ="0"/>
            <TRANSFORMFIELD DATATYPE ="string" DEFAULTVALUE ="" DESCRIPTION ="" GROUP ="DEFAULT" NAME ="MAPPLET_NAME2" PICTURETEXT ="" PORTTYPE ="OUTPUT" PRECISION ="50" REF_FIELD ="MAPPLET_NAME" SCALE ="0"/>
            <TRANSFORMFIELD DATATYPE ="string" DEFAULTVALUE ="" DESCRIPTION ="" GROUP ="DEFAULT" NAME ="DATADATE2" PICTURETEXT ="" PORTTYPE ="OUTPUT" PRECISION ="19" REF_FIELD ="DATADATE" SCALE ="0"/>
            <TABLEATTRIBUTE NAME ="Tracing Level" VALUE ="Normal"/>
        </TRANSFORMATION>
	 */
	// 重写获取output的方法
	protected void getDepOutput(String fieldName, Element fieldlement,
			Set<String> depFieldList)  {
		try {
			List<Element> refOutputElements = (List<Element>) XPath
					.selectNodes(fieldlement.getParentElement(),
							"./TRANSFORMFIELD[contains(@PORTTYPE, 'OUTPUT') and @REF_FIELD='"
									+ fieldName + "']");

			for (int i = 0; i < refOutputElements.size(); i++) {
				Element refOutputElement = refOutputElements.get(i);
				depFieldList.add(refOutputElement.getAttributeValue("NAME"));
			}
		} catch (JDOMException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

	}
}
